services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "100.97.52.112:5002:5000"
    volumes:
      - ./logs:/app/logs
      - type: bind
        source: ${PWD}/configurations
        target: /app/configurations
      - type: bind
        source: ${PWD}/backend/available_tags.txt
        target: /app/available_tags.txt        
      - processed_data:/tmp/csv_processor_output
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - PYTHONUNBUFFERED=1
      - GUNICORN_CMD_ARGS="--config=/app/gunicorn.conf.py"
      - HISTORIAN_SERVER=MELSRV01\\WIN911
      - HISTORIAN_USER=mpp
      - HISTORIAN_PASSWORD=Melissa2014
    extra_hosts:
      - "MELSRV01: 172.16.0.1"
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '2'
        reservations:
          memory: 4G
          cpus: '1'
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/status || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: on-failure:3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    networks:
      - app-network
      - mpp_server_default

  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "100.97.52.112:3002:3000"
      environment:
        - NODE_ENV=development
        - REACT_APP_API_URL=http://100.97.52.112:5002/api
      networks:
        - app-network

volumes:
  processed_data:

networks:
  app-network:
    driver: bridge
  mpp_server_default:
    external: true